# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{permissive}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Flip Sasser", "Simon Parsons"]
  s.date = %q{2009-11-01}
  s.description = %q{Permissive combines a model-based permissions system with bitmasking to
    create a flexible approach to maintaining permissions on your ActiveRecord
    models. It supports an easy-to-use set of methods for accessing and
    determining permissions, including some fun metaprogramming.}
  s.email = %q{flip@x451.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "VERSION"
  ]
  s.homepage = %q{http://github.com/flipsasser/permissive}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Permissive gives your ActiveRecord models granular permission support}
  s.test_files = [
    "spec/acts_as_permissive_spec.rb",
     "spec/permissions_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

